name: Build and Push Docker image

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Read image name from image.txt
      run: |
        echo "IMAGE_NAME=$(cat ${{ github.workspace }}/image.txt)" >> $GITHUB_ENV

    - name: Show image name (debug)
      run: echo "🟢 Image name is: ${{ env.IMAGE_NAME }}"

    - name: Get tag from ref
      run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ env.TAG }}

